index:
    path: /
    controller: App\Controller\IndexController::index
createOneLog:
    path: /createOneLog
    controller: App\Controller\LogController::createOneLog
createManyLogs:
    path: /createManyLogs
    controller: App\Controller\LogController::createManyLogs
createManyRandomLogs:
    path: /createManyRandomLogs
    controller: App\Controller\LogController::createManyRandomLogs

